### ISSUE TITLE
请问一下出现这个问题是怎么回事？

### ISSUE THREAD

**Issue by wayne0926** [RayWangQvQ/BiliBiliTool#154]
这是我在修改了配置文件后运行时出现的问题。（之前运行没问题）

这里是配置文件：

https://github.com/wayne0926/BiliBiliTool/blob/main/src/Ray.BiliBiliTool.Console/appsettings.json

这里是错误的日志：

```zsh
[11:44:21 INF] 版本号：1.0.10
[11:44:21 INF] 开源地址：https://github.com/RayWangQvQ/BiliBiliTool 

[11:44:21 INF] -----开始每日任务-----

[11:44:21 INF] ---开始【登录】---
[11:44:22 FTL] 程序发生异常：One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
Unhandled exception. System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
 ---> Refit.ApiException: Response status code does not indicate success: 412 (Precondition Failed).
   at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 267
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Ray.BiliBiliTool.DomainService.AccountDomainService.LoginByCookie() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.DomainService/AccountDomainService.cs:line 32
   at Ray.BiliBiliTool.Application.DailyTaskAppService.Login()
   at Ray.BiliBiliTool.Application.DailyTaskAppService.DoDailyTask() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Application/DailyTaskAppService.cs:line 56
   at Ray.BiliBiliTool.Console.Program.StartRun() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 94
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 29

```

**Comment by wayne0926** [comment]
好吧，重新运行又没问题了
