### ISSUE TITLE
One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)

### ISSUE THREAD

**Issue by maikebing** [RayWangQvQ/BiliBiliTool#205]
[16:47:41 INF] -----开始每日任务-----

[16:47:41 INF] ---开始【登录】---
[16:47:45 FTL] 程序发生异常：One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
Unhandled exception. System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
 ---> Refit.ApiException: Response status code does not indicate success: 412 (Precondition Failed).
   at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 267
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Ray.BiliBiliTool.DomainService.AccountDomainService.LoginByCookie() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.DomainService/AccountDomainService.cs:line 32
   at Ray.BiliBiliTool.Application.DailyTaskAppService.Login()
   at Ray.BiliBiliTool.Application.DailyTaskAppService.DoDailyTask() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Application/DailyTaskAppService.cs:line 56
   at Ray.BiliBiliTool.Console.Program.StartRun() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 94
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 29
Error: Process completed with exit code 134.

**Comment by ZSX-JOJO** [comment]
拉取最新的
更新完之后,我这里正常了

**Comment by RayWangQvQ** [comment]
[issues提交规范](https://github.com/RayWangQvQ/BiliBiliTool.Docs/blob/main/questions.md)
