### ISSUE TITLE
程序发生异常

### ISSUE THREAD

**Issue by ThinBuffalo** [RayWangQvQ/BiliBiliTool#238]
程序发生异常：One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
Unhandled exception. System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
 ---> Refit.ApiException: Response status code does not indicate success: 412 (Precondition Failed).
   at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 267
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Ray.BiliBiliTool.DomainService.AccountDomainService.LoginByCookie() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.DomainService/AccountDomainService.cs:line 32
   at Ray.BiliBiliTool.Application.DailyTaskAppService.Login()
   at Ray.BiliBiliTool.Application.DailyTaskAppService.DoDailyTask() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Application/DailyTaskAppService.cs:line 56
   at Ray.BiliBiliTool.Console.Program.StartRun() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 94
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 29
Error: Process completed with exit code 134.

**Comment by lumos2019** [comment]
+1 求解答

**Comment by DdwecPek** [comment]
http响应码412了，同问题

**Comment by TinQlo** [comment]
#61 看一下这个issue

**Comment by sxmcody** [comment]
遇到了同样的问题

**Comment by kai234** [comment]
+1

**Comment by zishuaiz** [comment]
+1

**Comment by sxmcody** [comment]
> #61 看一下这个issue
已经同步到1.0.13，还是412
-------------------------------------
[14:50:46 INF] 版本号：1.0.13
[14:50:46 INF] 开源地址：https://github.com/RayWangQvQ/BiliBiliTool 

[14:50:46 INF] -----开始每日任务-----

[14:50:46 INF] ---开始【登录】---
[14:50:50 FTL] 程序发生异常：One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
Unhandled exception. System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)

**Comment by NjshawnYue1** [comment]
> > #61 看一下这个issue
> > 已经同步到1.0.13，还是412
> 
> [14:50:46 INF] 版本号：1.0.13
> [14:50:46 INF] 开源地址：https://github.com/RayWangQvQ/BiliBiliTool
> 
> [14:50:46 INF] -----开始每日任务-----
> 
> [14:50:46 INF] ---开始【登录】---
> [14:50:50 FTL] 程序发生异常：One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
> Unhandled exception. System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)

这个仓库怎么同步的

**Comment by sxmcody** [comment]
> > > #61 看一下这个issue
> > > 已经同步到1.0.13，还是412
> > 
> > 
> > [14:50:46 INF] 版本号：1.0.13
> > [14:50:46 INF] 开源地址：https://github.com/RayWangQvQ/BiliBiliTool
> > [14:50:46 INF] -----开始每日任务-----
> > [14:50:46 INF] ---开始【登录】---
> > [14:50:50 FTL] 程序发生异常：One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
> > Unhandled exception. System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
> 
> 这个仓库怎么同步的

就是pull request，步骤的话可以看这个帖子，纸飞机那个说的很详细[https://www.zhihu.com/question/28676261/answer/44606041](url)

**Comment by NjshawnYue1** [comment]
> > > > #61 看一下这个issue
> > > > 已经同步到1.0.13，还是412
> > > 
> > > 
> > > [14:50:46 INF] 版本号：1.0.13
> > > [14:50:46 INF] 开源地址：https://github.com/RayWangQvQ/BiliBiliTool
> > > [14:50:46 INF] -----开始每日任务-----
> > > [14:50:46 INF] ---开始【登录】---
> > > [14:50:50 FTL] 程序发生异常：One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
> > > Unhandled exception. System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
> > 
> > 
> > 这个仓库怎么同步的
> 
> 就是pull request，步骤的话可以看这个帖子，纸飞机那个说的很详细[https://www.zhihu.com/question/28676261/answer/44606041](url)

操作了一边感觉不是很对

**Comment by Immity** [comment]
+1
16:18:10 INF] 版本号：1.0.13
[16:18:10 INF] 开源地址：https://github.com/RayWangQvQ/BiliBiliTool 

[16:18:11 INF] -----开始每日任务-----

[16:18:11 INF] ---开始【登录】---
[16:18:17 FTL] 程序发生异常：One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
Unhandled exception. System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
 ---> Refit.ApiException: Response status code does not indicate success: 412 (Precondition Failed).
   at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 267
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Ray.BiliBiliTool.DomainService.AccountDomainService.LoginByCookie() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.DomainService/AccountDomainService.cs:line 32
   at Ray.BiliBiliTool.Application.DailyTaskAppService.Login()
   at Ray.BiliBiliTool.Application.DailyTaskAppService.DoDailyTask() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Application/DailyTaskAppService.cs:line 56
   at Ray.BiliBiliTool.Console.Program.StartRun() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 94
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 29
Aborted (core dumped)

**Comment by Twinzo1** [comment]
同步了源码后，正常了

**Comment by sxmcody** [comment]
> 同步了源码后，正常了

+1

**Comment by BeiChuang518** [comment]
同步后正常~
