### ISSUE TITLE
程序报错：One or more errors occurred. (Resource temporarily unavailable (api.bilibili.com:443))

### ISSUE THREAD

**Issue by FunkyPantsSa** [RayWangQvQ/BiliBiliTool#317]
开发者你好，
我使用的是阿里云的云服务器 docker 运行脚本。同时有两个账号，之前运行正常，运行正常两天后突然报错（报错信息如下）。我尝试了重启 docker，以及重新起一个 docker。但是依旧有这样的错误。翻看了一下 issue，好像没有和我一样的问题。

希望能够有所帮助。十分感谢您。
软件的版本为1.0.14

```yml
[06:06:57 INF] ---开始【登录】---
[06:07:14 ERR] 程序发生异常：One or more errors occurred. (Resource temporarily unavailable (api.bilibili.com:443))
Unhandled exception. System.AggregateException: One or more errors occurred. (Resource temporarily unavailable (sc.ftqq.com:80))
 ---> System.Net.Http.HttpRequestException: Resource temporarily unavailable (sc.ftqq.com:80)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 245
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Ray.BiliBiliTool.Agent.ServerChanAgent.PushService.DoSend(String title, String content) in /src/Ray.BiliBiliTool.Agent/ServerChanAgent/PushService.cs:line 27
   at Ray.BiliBiliTool.Agent.ServerChanAgent.PushService.SendStringWriter() in /src/Ray.BiliBiliTool.Agent/ServerChanAgent/PushService.cs:line 37
   at Ray.BiliBiliTool.Console.Program.StartRun() in /src/Ray.BiliBiliTool.Console/Program.cs:line 105
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /src/Ray.BiliBiliTool.Console/Program.cs:line 28
/bilibili/job.sh: line 15:    83 Aborted                 (core dumped) /bilibili/Ray.BiliBiliTool.Console -closeConsoleWhenEnd=1
Execution finished

```

我依旧在尝试一下自己排查一下是什么问题，并解决它。希望您能够给出更加专业的指导。

**Comment by hjkl950217** [comment]
可以试试换个环境跑docker看看，我用github action跑的好的。
也许是阿里云的网络环境导致的？

**Comment by FunkyPantsSa** [comment]
> 可以试试换个环境跑docker看看，我用github action跑的好的。
> 也许是阿里云的网络环境导致的？先排除一下是不是环境问题。。

我试试本地跑 docker 试试

**Comment by FunkyPantsSa** [comment]
本地 docker 可以正常跑。
我升级到了 1.0.15， 报错为 ssl 链接失败。想必也是这个问题吧。
目前使用的是 1.0.15 版本在本地运行。以及本地运行 1.0.14的 docker 版本。
此贴终结。
