### ISSUE TITLE
全部任务已执行结束，但任务提示：Error: Process completed with exit code 134

### ISSUE THREAD

**Issue by yinghualuowu** [RayWangQvQ/BiliBiliTool#341]
版本号：1.0.17
执行任务链接：https://github.com/yinghualuowu/BiliBiliTool/runs/1608901744?check_suite_focus=true
结果：全部任务已执行结束，但任务提示：Error: Process completed with exit code 134，收到了任务失败的邮件

**Comment by RayWangQvQ** [comment]
Server酱推送挂了，如果以前推送成功过（即配置是正确的），那么极有可能是Server酱的服务器发生偶发性异常，以前也出现过几次。
下个版本的推送会增加企业微信、钉钉和Telegram等推送端，可以自由选择一个或多个推送端。

**Comment by LittleNightmare** [comment]
我这边也是，但任务好像失败，卡在登陆上。我没用server酱
```
[23:46:23 INF] ---开始【登录】---
[23:48:***3 ERR] 程序发生异常：One or more errors occurred. (A task was canceled.)
Unhandled exception. System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Ray.BiliBiliTool.DomainService.AccountDomainService.LoginByCookie() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.DomainService/AccountDomainService.cs:line 36
   at Ray.BiliBiliTool.Application.DailyTaskAppService.Login()
   at Ray.BiliBiliTool.Application.DailyTaskAppService.DoDailyTask() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Application/DailyTaskAppService.cs:line ***9
   at Ray.BiliBiliTool.Console.Program.StartRun() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 1***2
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 28
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Ray.BiliBiliTool.DomainService.AccountDomainService.LoginByCookie() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.DomainService/AccountDomainService.cs:line 36
   at Ray.BiliBiliTool.Application.DailyTaskAppService.Login()
   at Ray.BiliBiliTool.Application.DailyTaskAppService.DoDailyTask() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Application/DailyTaskAppService.cs:line ***9
   at Ray.BiliBiliTool.Console.Program.StartRun() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 1***2
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 28
/home/runner/work/_temp/9f4a14***8-***fc***-42e9-984***-***bc6393fd2b1.sh: line 2:  3***96 Aborted                 (core dumped) dotnet Ray.BiliBiliTool.Console.dll -closeConsoleWhenEnd=1
Error: Process completed with exit code 134.
```

**Comment by RayWangQvQ** [comment]
v1.1.x支持多个平台的推送，担心Server酱偶尔挂掉的，建议更新升级到最新版本。
