### ISSUE TITLE
docker-compose启动执行后日志报错

### ISSUE THREAD

**Issue by solar24** [RayWangQvQ/BiliBiliTool#515]
2021-03-12 14:10:10.421 +08:00 [INF] ---开始【登录】---
2021-03-12 14:13:10.454 +08:00 [ERR] 程序发生异常：The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
2021-03-12 14:13:10.456 +08:00 [ERR] 程序异常终止，原因：The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
2021-03-12 14:13:10.458 +08:00 [INF] 开始推送
2021-03-12 14:13:10.459 +08:00 [INF] 正在自动关闭应用...
2021-03-12 14:13:10.463 +08:00 [FTL] Host terminated unexpectedly!
System.Net.Http.HttpRequestException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Ray.BiliBiliTool.Agent.HttpClientDelegatingHandlers.IntervalDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /src/Ray.BiliBiliTool.Agent/HttpClientDelegatingHandlers/IntervalDelegatingHandler.cs:line 24
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at WebApiClientCore.Implementations.ApiRequestSender.SendAsync(ApiRequestContext context)
   at WebApiClientCore.Implementations.ApiRequestExecuter.ExecuteAsync(ApiRequestContext request)
   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(ApiRequestContext request)
   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(HttpClientContext context, Object[] arguments)
   --- End of inner exception stack trace ---
   at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(HttpClientContext context, Object[] arguments)
   at Ray.BiliBiliTool.DomainService.AccountDomainService.LoginByCookie() in /src/Ray.BiliBiliTool.DomainService/AccountDomainService.cs:line 45
   at Ray.BiliBiliTool.Application.DailyTaskAppService.Login()
   at Ray.BiliBiliTool.Application.DailyTaskAppService.DoDailyTask() in /src/Ray.BiliBiliTool.Application/DailyTaskAppService.cs:line 68
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 44
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /src/Ray.BiliBiliTool.Console/Program.cs:line 25

**Comment by RayWangQvQ** [comment]
看样子是网络不通，http请求超时后报异常了。

建议在容器内ping下外网试试，确保网络是通的。
