### ISSUE TITLE
【Bug】休眠时间过长导致登录超时？

### ISSUE THREAD

**Issue by seiuneko** [RayWangQvQ/BiliBiliTool#547]
版本号：1.2.6.r4.ga501d07-1
运行环境：Arch Linux (AUR)
问题描述：如题
日志信息：
<details><summary>log</summary>
<p>

```
BiliBiliTool Log, [06.04.21 09:56]
Ray.BiliBiliTool任务推送

ℹ️ 【版本号】Ray.BiliBiliTool-v1.2.6
ℹ️ 【当前IP】** 
ℹ️ 【开源地址】 github.com/RayWangQvQ/BiliBiliTool

ℹ️ 随机休眠28分钟

ℹ️ -----开始 每日任务 -----

ℹ️ ---开始 登录 ---
❗️ [REQUEST]
GET /x/web-interface/nav HTTP/1.1
Referer: https://www.bilibili.com/
Origin: https://www.bilibili.com
Host: api.bilibili.com
Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Connection: keep-alive

[EXCEPTION]
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Ray.BiliBiliTool.Agent.HttpClientDelegatingHandlers.IntervalDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /home/orange/.cache/yay/bilibilitool-dotnet-git/src/bilibilitool-dotnet/src/Ray.BiliBiliTool.Agent/HttpClientDelegatingHandlers/IntervalDelegatingHandler.cs:line 30
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at WebApiClientCore.Implementations.ApiRequestSender.SendCoreAsync(ApiRequestContext context)
   at WebApiClientCore.Implementations.ApiRequestSender.SendAsync(ApiRequestContext context)

[ELAPSED] 00:02:06.1566502
❗️ 程序发生异常：The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
❗️ 程序发生异常：The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
❗️ 程序异常终止，原因：The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
ℹ️ 开始推送
```

<br>

```
BiliBiliTool Log, [07.04.21 15:52]
Ray.BiliBiliTool任务推送

ℹ️ 【版本号】Ray.BiliBiliTool-v1.2.6
ℹ️ 【当前IP】** 
ℹ️ 【开源地址】 github.com/RayWangQvQ/BiliBiliTool

ℹ️ 随机休眠12分钟

ℹ️ -----开始 每日任务 -----

ℹ️ ---开始 登录 ---
❗️ [REQUEST]
GET /x/web-interface/nav HTTP/1.1
Referer: https://www.bilibili.com/
Origin: https://www.bilibili.com
Host: api.bilibili.com
Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Connection: keep-alive

[EXCEPTION]
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Ray.BiliBiliTool.Agent.HttpClientDelegatingHandlers.IntervalDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /home/orange/.cache/yay/bilibilitool-dotnet-git/src/bilibilitool-dotnet/src/Ray.BiliBiliTool.Agent/HttpClientDelegatingHandlers/IntervalDelegatingHandler.cs:line 30
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at WebApiClientCore.Implementations.ApiRequestSender.SendCoreAsync(ApiRequestContext context)
   at WebApiClientCore.Implementations.ApiRequestSender.SendAsync(ApiRequestContext context)

[ELAPSED] 00:01:51.1273174
❗️ 程序发生异常：The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
❗️ 程序发生异常：The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
❗️ 程序异常终止，原因：The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
ℹ️ 开始推送
```

<br>

```
BiliBiliTool Log, [10.04.21 15:31]
Ray.BiliBiliTool任务推送

ℹ️ 【版本号】Ray.BiliBiliTool-v1.2.6
ℹ️ 【当前IP】** 
ℹ️ 【开源地址】 github.com/RayWangQvQ/BiliBiliTool

ℹ️ 随机休眠25分钟

ℹ️ -----开始 每日任务 -----

ℹ️ ---开始 登录 ---
❗️ [REQUEST]
GET /x/web-interface/nav HTTP/1.1
Referer: https://www.bilibili.com/
Origin: https://www.bilibili.com
Host: api.bilibili.com
Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Connection: keep-alive

[EXCEPTION]
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Ray.BiliBiliTool.Agent.HttpClientDelegatingHandlers.IntervalDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /home/orange/.cache/yay/bilibilitool-dotnet-git/src/bilibilitool-dotnet/src/Ray.BiliBiliTool.Agent/HttpClientDelegatingHandlers/IntervalDelegatingHandler.cs:line 30
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at WebApiClientCore.Implementations.ApiRequestSender.SendCoreAsync(ApiRequestContext context)
   at WebApiClientCore.Implementations.ApiRequestSender.SendAsync(ApiRequestContext context)

[ELAPSED] 00:01:45.0980732
❗️ 程序发生异常：The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
❗️ 程序发生异常：The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
❗️ 程序异常终止，原因：The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
ℹ️ 开始推送
```

</p>
</details>

**Comment by RayWangQvQ** [comment]
跟休眠无关

**Comment by seiuneko** [comment]
更新下 Cookie 后正常了。
但之前在没有设置休眠延迟时却可以正常执行。

**Comment by seiuneko** [comment]
当有延迟时依旧会触发此问题

**Comment by RayWangQvQ** [comment]
> 当有延迟时依旧会触发此问题

我个人还是认为跟休眠没有关系。

你可以自己试着证明下，假设如果是休眠造成的，那么应该能实现下面的情况：

**关闭休眠（休眠等于0）时，运行应用，日志显示成功；
然后开启休眠（时间大于0），再次运行，日志立即显示失败。
然后再次关闭，运行，日志又显示成功。**

你可以试试看，看能不能得出这样的日志。

**Comment by seiuneko** [comment]
确实与休眠没有关系 

触发条件是 IntervalSecondsBetweenRequestApi >= 100 

（另外可不可以加个类似于 --debug 的选项方便调试？
（另外可不可以处理 Ctrl+C 发送的 SIGINT 信号？
