### ISSUE TITLE
程序发生异常：登录失败，请检查Cookie

### ISSUE THREAD

**Issue by windskyxb** [RayWangQvQ/BiliBiliTool#554]
版本号：v1.2.7
运行环境：本地 Windows10

问题描述：一直提示登录失败，请检查cookie。浏览器重新登录获取cookie后也是同样的问题

日志信息：2021-04-15 12:17:34.662 +08:00 [INF] 【版本号】Ray.BiliBiliTool-v1.2.7
2021-04-15 12:17:35.402 +08:00 [INF] 【当前IP】180.137.17.114 
2021-04-15 12:17:35.403 +08:00 [INF] 【开源地址】 github.com/RayWangQvQ/BiliBiliTool

2021-04-15 12:17:35.405 +08:00 [INF] 随机休眠24分钟

2021-04-15 12:41:35.411 +08:00 [INF] =====开始 每日任务 =====

2021-04-15 12:41:35.412 +08:00 [INF] ---开始 登录 ---
2021-04-15 12:42:14.800 +08:00 [DBG] [REQUEST]
GET /x/web-interface/nav HTTP/1.1
Referer: https://www.bilibili.com/
Origin: https://www.bilibili.com
Host: api.bilibili.com
Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Connection: keep-alive

[RESPONSE]
HTTP/1.1 200 OK
Date: Thu, 15 Apr 2021 04:42:16 GMT
Connection: keep-alive
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET,POST
Access-Control-Allow-Origin: https://www.bilibili.com
Bili-Status-Code: -101
Bili-Trace-Id: 200a24be16077c4
Vary: Origin
Access-Control-Allow-Headers: Origin,No-Cache,X-Requested-With,If-Modified-Since,Pragma,Last-Modified,Cache-Control,Expires,Content-Type,Access-Control-Allow-Credentials,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Cache-Webcdn,x-bilibili-key-real-ip,x-backend-bili-real-ip
Access-Control-Expose-Headers: X-Cache-Webcdn
Cache-Control: no-cache
X-Cache-Webcdn: BYPASS from hw-gz3-webcdn-09
Content-Type: application/json; charset=utf-8
Content-Length: 74
Expires: Thu, 15 Apr 2021 04:42:15 GMT

{"code":-101,"message":"账号未登录","ttl":1,"data":{"isLogin":false}}

[ELAPSED] 00:00:39.3719967
2021-04-15 12:42:14.802 +08:00 [WRN] 登录异常，请检查Cookie是否错误或过期
2021-04-15 12:42:14.803 +08:00 [ERR] 程序发生异常：登录失败，请检查Cookie
2021-04-15 12:42:14.805 +08:00 [ERR] 程序发生异常：登录失败，请检查Cookie
2021-04-15 12:42:14.805 +08:00 [ERR] 程序异常终止，原因：登录失败，请检查Cookie
2021-04-15 12:42:14.806 +08:00 [INF] 开始推送
2021-04-15 12:42:14.810 +08:00 [FTL] Host terminated unexpectedly!
System.Exception: 登录失败，请检查Cookie
   at Ray.BiliBiliTool.Application.DailyTaskAppService.Login()
   at Ray.BiliBiliTool.Application.DailyTaskAppService.DoTask()
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 65
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 26
2021-04-15 12:59:15.925 +08:00 [INF] 【版本号】Ray.BiliBiliTool-v1.2.7
2021-04-15 12:59:16.662 +08:00 [INF] 【当前IP】180.137.17.114 
2021-04-15 12:59:16.663 +08:00 [INF] 【开源地址】 github.com/RayWangQvQ/BiliBiliTool

2021-04-15 12:59:16.664 +08:00 [INF] 随机休眠2分钟

2021-04-15 13:01:16.668 +08:00 [INF] =====开始 每日任务 =====

2021-04-15 13:01:16.670 +08:00 [INF] ---开始 登录 ---
2021-04-15 13:01:52.066 +08:00 [DBG] [REQUEST]
GET /x/web-interface/nav HTTP/1.1
Referer: https://www.bilibili.com/
Origin: https://www.bilibili.com
Host: api.bilibili.com
Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Connection: keep-alive

[RESPONSE]
HTTP/1.1 200 OK
Date: Thu, 15 Apr 2021 05:01:53 GMT
Connection: keep-alive
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET,POST
Access-Control-Allow-Origin: https://www.bilibili.com
Bili-Status-Code: -101
Bili-Trace-Id: 25cfeea5f86077c8
Vary: Origin
Access-Control-Allow-Headers: Origin,No-Cache,X-Requested-With,If-Modified-Since,Pragma,Last-Modified,Cache-Control,Expires,Content-Type,Access-Control-Allow-Credentials,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Cache-Webcdn
IDC: shjd
Set-Cookie: bfe_id=5db70a86bd1cbe8a88817507134f7bb5; Path=/; Max-Age=600; Expires=Thu, 15-Apr-21 05:11:53 GMT
Cache-Control: no-cache
X-Cache-Webcdn: BYPASS from hw-gz3-webcdn-02
Content-Type: application/json; charset=utf-8
Content-Length: 74
Expires: Thu, 15 Apr 2021 05:01:52 GMT

{"code":-101,"message":"账号未登录","ttl":1,"data":{"isLogin":false}}

[ELAPSED] 00:00:35.3796171
2021-04-15 13:01:52.068 +08:00 [WRN] 登录异常，请检查Cookie是否错误或过期
2021-04-15 13:01:52.069 +08:00 [ERR] 程序发生异常：登录失败，请检查Cookie
2021-04-15 13:01:52.070 +08:00 [ERR] 程序发生异常：登录失败，请检查Cookie
2021-04-15 13:01:52.071 +08:00 [ERR] 程序异常终止，原因：登录失败，请检查Cookie
2021-04-15 13:01:52.072 +08:00 [INF] 开始推送
2021-04-15 13:01:52.077 +08:00 [FTL] Host terminated unexpectedly!
System.Exception: 登录失败，请检查Cookie
   at Ray.BiliBiliTool.Application.DailyTaskAppService.Login()
   at Ray.BiliBiliTool.Application.DailyTaskAppService.DoTask()
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 65
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 26

**Comment by RayWangQvQ** [comment]
https://github.com/RayWangQvQ/BiliBiliTool#11-%E7%AC%AC%E4%B8%80%E6%AD%A5%E8%8E%B7%E5%8F%96%E8%87%AA%E5%B7%B1%E7%9A%84-cookie

**Comment by RayWangQvQ** [comment]
无跟进
