### ISSUE TITLE
【Bug】在云函数使用自动触发出现异常 但手动点测试运行正常

### ISSUE THREAD

**Issue by untiluuu** [RayWangQvQ/BiliBiliTool#585]
版本号：2.0.1
运行环境：云函数

问题描述：在云函数使用自动触发出现异常 但手动点运行正常

日志信息：[00:07:06 WRN] 异常：System.Collections.Generic.KeyNotFoundException: The given key ',' was not present in the dictionary.

   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)

   at Ray.BiliBiliTool.Console.HostedServices.BiliBiliToolHostedService.DoTasks(String[] tasks) in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/HostedServices/BiliBiliToolHostedService.cs:line 90

   at Ray.BiliBiliTool.Console.HostedServices.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/HostedServices/BiliBiliToolHostedService.cs:line 52

**Comment by RayWangQvQ** [comment]
触发器的`附加信息`填的啥

**Comment by untiluuu** [comment]
刚刚检查了 触发器附加信息 打错了 谢谢大佬 已解决！
