### ISSUE TITLE
412请求拦截

### ISSUE THREAD

**Issue by luojian1996** [RayWangQvQ/BiliBiliTool#586]
版本号：bilibili-tool-v2.0.1-tencent-scf
运行环境：Tencent scf

问题描述：（{"code":-412,"message":"请求被拦截","ttl":1,"data":null}

日志信息：
<html>
<body>

[09:31:49 ERR] [REQUEST]
--
GET /xlive/web-interface/v1/second/getList?platform=web&parent_area_id=2&area_id=0&sort_type=sort_type_124&page=2 HTTP/1.1
Referer: https://live.bilibili.com/
Origin: https://live.bilibili.com
Host: api.live.bilibili.com
Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Connection: keep-alive
Sec-Fetch-Site: same-site
 
[RESPONSE]
HTTP/1.1 412 Precondition Failed
Date: Wed, 12 May 2021 09:31:49 GMT
Connection: keep-alive
Server: openresty
Content-Type: application/json
Content-Length: 61
 
 
{"code":-412,"message":"请求被拦截","ttl":1,"data":null}
[EXCEPTION]
WebApiClientCore.Exceptions.ApiResponseStatusException: 服务器响应了错误的http状态码：412 Precondition Failed
at WebApiClientCore.Attributes.ApiReturnAttribute.ValidateResponseStatusCode(HttpResponseMessage response)
at WebApiClientCore.Attributes.ApiReturnAttribute.ValidateResponseAsync(ApiResponseContext context)
at WebApiClientCore.Attributes.ApiReturnAttribute.OnResponseAsync(ApiResponseContext context)
at WebApiClientCore.Implementations.ApiRequestExecuter.HandleResponseAsync(ApiResponseContext context)
 
[ELAPSED] 00:00:15.2375350
[09:31:49 ERR] 程序发生异常：服务器响应了错误的http状态码：412 Precondition Failed
[09:31:49 ERR] 程序发生异常：服务器响应了错误的http状态码：412 Precondition Failed
[09:31:49 WRN] 异常：System.Net.Http.HttpRequestException: 服务器响应了错误的http状态码：412 Precondition Failed
---> WebApiClientCore.Exceptions.ApiResponseStatusException: 服务器响应了错误的http状态码：412 Precondition Failed
at WebApiClientCore.Attributes.ApiReturnAttribute.ValidateResponseStatusCode(HttpResponseMessage response)
at WebApiClientCore.Attributes.ApiReturnAttribute.ValidateResponseAsync(ApiResponseContext context)
at WebApiClientCore.Attributes.ApiReturnAttribute.OnResponseAsync(ApiResponseContext context)
at WebApiClientCore.Implementations.ApiRequestExecuter.HandleResponseAsync(ApiResponseContext context)
at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(ApiRequestContext request)
at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(HttpClientContext context, Object[] arguments)
--- End of inner exception stack trace ---
at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(HttpClientContext context, Object[] arguments)
at Ray.BiliBiliTool.DomainService.LiveDomainService.TianXuan() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.DomainService/LiveDomainService.cs:line 150
at Ray.BiliBiliTool.Application.LiveLotteryTaskAppService.LotteryTianXuan()
at Ray.BiliBiliTool.Application.LiveLotteryTaskAppService.DoTask()
at Ray.BiliBiliTool.Console.HostedServices.BiliBiliToolHostedService.DoTasks(String[] tasks) in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/HostedServices/BiliBiliToolHostedService.cs:line 91
at Ray.BiliBiliTool.Console.HostedServices.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/HostedServices/BiliBiliToolHostedService.cs:line 52
[09:31:49 INF] 开始推送
[09:31:49 INF] 正在自动关闭应用...

</body>
</html>

**Comment by RayWangQvQ** [comment]
* 更新Cookie
* 添加UA

**Comment by RayWangQvQ** [comment]
无跟进
