### ISSUE TITLE
近期程序登录时报412 (Precondition Failed)异常

### ISSUE THREAD

**Issue by su316** [RayWangQvQ/BiliBiliTool#61]
FTL] 程序发生异常：One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)

**Comment by webfamer** [comment]
我是改了一下投币数，把5改成了1，然后就报异常了

**Comment by yinghualuowu** [comment]
如果是登录异常，烦请拉取最新代码就可以正常运行了~
```
[14:27:50 INF] ---开始【登录】---
[14:27:50 FTL] 程序发生异常：One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
```

**Comment by ZijingMao** [comment]
412请求被拦截，可能是ip问题

**Comment by su316** [comment]
> 如果是登录异常，烦请拉取最新代码就可以正常运行了〜
> 
> ```
> [14:27:50 INF] ---开始【登录】---
> [14:27:50 FTL] 程序发生异常：One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
> ```

是重新获取Cookie么？

**Comment by yinghualuowu** [comment]
> > 如果是登录异常，烦请拉取最新代码就可以正常运行了〜
> > ```
> > [14:27:50 INF] ---开始【登录】---
> > [14:27:50 FTL] 程序发生异常：One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
> > ```
> 
> 是重新获取Cookie么？

看不到你的fork项目，不知道后面的报错是什么。如果单单是上面的报错，可以拉取最新代码在跑一下。cookie如果有效不用再次更新的

**Comment by yinghualuowu** [comment]
> > 如果是登录异常，烦请拉取最新代码就可以正常运行了〜
> > ```
> > [14:27:50 INF] ---开始【登录】---
> > [14:27:50 FTL] 程序发生异常：One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
> > ```
> 
> 是重新获取Cookie么？

不用，我今天也遇见了，后面更新了代码重新执行就没问题了。

**Comment by su316** [comment]
> > > 如果是登录异常，烦请拉取最新代码就可以正常运行了〜
> > > ```
> > > [14:27:50 INF] ---开始【登录】---
> > > [14:27:50 FTL] 程序发生异常：One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
> > > ```
> > 
> > 
> > 是重新获取Cookie么？
> 
> 不用，我今天也遇见了，后面更新了代码重新执行就没问题了。

更新了代码？我重新下载了新版的压缩包，看不懂，没有启动程序，重新执行是在哪里操作呢？

**Comment by su316** [comment]
![image](https://user-images.githubusercontent.com/59133203/99782600-55b36700-2b54-11eb-9036-133471d2b421.png)
[``](url)

**Comment by q309294987** [comment]
> ![image](https://user-images.githubusercontent.com/59133203/99782600-55b36700-2b54-11eb-9036-133471d2b421.png)
> [``](url)

更新fork代码，然后更新一下cookie就行。

**Comment by su316** [comment]
> > ![图片](https://user-images.githubusercontent.com/59133203/99782600-55b36700-2b54-11eb-9036-133471d2b421.png)
> > [``](url)
> 
> 更新fork代码，然后更新一下cookie就行。

请问怎么更新更新fork代码呢？我小白一个

**Comment by q309294987** [comment]
> > > ![图片](https://user-images.githubusercontent.com/59133203/99782600-55b36700-2b54-11eb-9036-133471d2b421.png)
> > > [``](url)
> > 
> > 
> > 更新fork代码，然后更新一下cookie就行。
> 
> 请问怎么更新更新fork代码呢？我小白一个

百度：如何更新github fork代码

**Comment by RayWangQvQ** [comment]
当前版本添加了UA的配置项用于暂时解决登录报412的异常，详情请点击 [常见问题4](https://github.com/RayWangQvQ/BiliBiliTool.Docs/blob/main/questions.md) 查看。

**Comment by zerospaceeee** [comment]
![image](https://user-images.githubusercontent.com/26269474/100472924-03150600-3092-11eb-9e83-bf733a9bbf4c.png)

**Comment by zerospaceeee** [comment]
改过UA还是不行，海外的IP

**Comment by myx75** [comment]
360会认为是木马，然后信任手执行程序报错了：

[08:31:07 INF] 版本号：1.0.10
[08:31:07 INF] 开源地址：https://github.com/RayWangQvQ/BiliBiliTool

[08:31:07 INF] -----开始每日任务-----

[08:31:07 INF] ---开始【登录】---
[08:31:07 FTL] **程序发生异常：One or more errors occurred**. (Response status code does not indicate success: 412 (Precondition Failed).)
Unhandled exception. System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
 ---> Refit.ApiException: Response status code does not indicate success: 412 (Precondition Failed).
   at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 267
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Ray.BiliBiliTool.DomainService.AccountDomainService.LoginByCookie() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.DomainService/AccountDomainService.cs:line 32
   at Ray.BiliBiliTool.Application.DailyTaskAppService.Login()
   at Ray.BiliBiliTool.Application.DailyTaskAppService.DoDailyTask() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Application/DailyTaskAppService.cs:line 56
   at Ray.BiliBiliTool.Console.Program.StartRun() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 94
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 29

**Comment by myx75** [comment]
> 360会认为是木马，然后信任后执行程序报错了：
> 
> [08:31:07 INF] 版本号：1.0.10
> [08:31:07 INF] 开源地址：https://github.com/RayWangQvQ/BiliBiliTool
> 
> [08:31:07 INF] -----开始每日任务-----
> 
> [08:31:07 INF] ---开始【登录】---
> [08:31:07 FTL] **程序发生异常：One or more errors occurred**. (Response status code does not indicate success: 412 (Precondition Failed).)
> Unhandled exception. System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
> ---> Refit.ApiException: Response status code does not indicate success: 412 (Precondition Failed).
> at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 267 --- End of inner exception stack trace --- at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
> at System.Threading.Tasks.Task`1.get_Result()
> at Ray.BiliBiliTool.DomainService.AccountDomainService.LoginByCookie() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.DomainService/AccountDomainService.cs:line 32
> at Ray.BiliBiliTool.Application.DailyTaskAppService.Login()
> at Ray.BiliBiliTool.Application.DailyTaskAppService.DoDailyTask() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Application/DailyTaskAppService.cs:line 56
> at Ray.BiliBiliTool.Console.Program.StartRun() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 94
> at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 29

换了另外一个IP可以使用了，大概率是被屏蔽了，想使用的朋友及时用，不知道何时会被注意到。

**Comment by flyketch** [comment]
[14:39:01 FTL] 程序发生异常：One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
Unhandled exception. System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
 ---> Refit.ApiException: Response status code does not indicate success: 412 (Precondition Failed).
   at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 267
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Ray.BiliBiliTool.DomainService.AccountDomainService.LoginByCookie() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.DomainService/AccountDomainService.cs:line 32
   at Ray.BiliBiliTool.Application.DailyTaskAppService.Login()
   at Ray.BiliBiliTool.Application.DailyTaskAppService.DoDailyTask() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Application/DailyTaskAppService.cs:line 56
   at Ray.BiliBiliTool.Console.Program.StartRun() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 94
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 29
Error: Process completed with exit code 134.

**Comment by RayWangQvQ** [comment]
平反下，跟B站风控可能没有关系，跟User Agent也无关，之前改UA可能只是巧合。
最新发现，可能跟nav接口传递referer头部有关。
当前已于v1.0.13版本解决412异常，从目前根据反馈看，大家升级到1.0.13版本后都没有出现过412异常了，后续待进一步观察。
再有412异常的，请先确认自己的版本是否大于等于v1.0.13

**Comment by heyiWF** [comment]
> 平反下，跟B站风控可能没有关系，跟User Agent也无关，之前改UA可能只是巧合。
> 最新发现，可能跟nav接口传递referer头部有关。
> 当前已于v1.0.13版本解决412异常，从目前根据反馈看，大家升级到1.0.13版本后都没有出现过412异常了，后续待进一步观察。
> 再有412异常的，请先确认自己的版本是否大于等于v1.0.13

![Screenshot 2020-12-01 110928](https://user-images.githubusercontent.com/45261950/100692531-07109300-33c6-11eb-9f69-01c092a00718.png)

已同步v1.0.13版本，仍出现412异常。Cookies没有改动。

**Comment by Kexueguaixiong** [comment]
已同步v1.0.13版本，仍出现412异常。Cookies没有改动。

**Comment by seiuneko** [comment]
已同步 v1.0.13 版本，仍出现 412 异常。Cookies 没有改动。

**Comment by zhou-xiansen** [comment]
> 平反下，跟B站风控可能没有关系，跟User Agent也无关，之前改UA可能只是巧合。
> 最新发现，可能跟nav接口传递referer头部有关。
> 当前已于v1.0.13版本解决412异常，从目前根据反馈看，大家升级到1.0.13版本后都没有出现过412异常了，后续待进一步观察。
> 再有412异常的，请先确认自己的版本是否大于等于v1.0.13

更新到最新版本，1.0.13依然412报错

**Comment by Kexueguaixiong** [comment]
![image](https://user-images.githubusercontent.com/74920486/100694635-7092a080-33ca-11eb-944c-c2f78b94b412.jpg)
版本已更新，没有变cookie。

**Comment by xcsyy** [comment]
已拉取最新的1.0.13版本，依然报错412

**Comment by xcsyy** [comment]
> 已拉取最新的1.0.13版本，依然报错412

![image](https://user-images.githubusercontent.com/72963211/100702729-2ff05280-33dd-11eb-9f9e-756be2890484.png)

**Comment by lumos2019** [comment]
已拉取最新的1.0.13版本，依然报错412
![微信截图_20201201141813](https://user-images.githubusercontent.com/66518889/100704522-9e82df80-33e0-11eb-92b6-aa5b877639b7.png)

**Comment by wysnxzm** [comment]
412

**Comment by w2131978** [comment]
412异常

[16:03:11 FTL] 程序发生异常：One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
Unhandled exception. System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
 ---> Refit.ApiException: Response status code does not indicate success: 412 (Precondition Failed).
   at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 267
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Ray.BiliBiliTool.DomainService.AccountDomainService.LoginByCookie() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.DomainService/AccountDomainService.cs:line 32
   at Ray.BiliBiliTool.Application.DailyTaskAppService.Login()
   at Ray.BiliBiliTool.Application.DailyTaskAppService.DoDailyTask() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Application/DailyTaskAppService.cs:line 56
   at Ray.BiliBiliTool.Console.Program.StartRun() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 94
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 29
Error: Process completed with exit code 134.

**Comment by LegendAdmin** [comment]
[16:18:15 INF] 版本号：1.0.13
[16:18:15 INF] 开源地址：https://github.com/RayWangQvQ/BiliBiliTool 

[16:18:15 INF] -----开始每日任务-----

[16:18:15 INF] ---开始【登录】---
[16:18:19 FTL] 程序发生异常：One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
Unhandled exception. System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
 ---> Refit.ApiException: Response status code does not indicate success: 412 (Precondition Failed).
   at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 267
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Ray.BiliBiliTool.DomainService.AccountDomainService.LoginByCookie() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.DomainService/AccountDomainService.cs:line 32
   at Ray.BiliBiliTool.Application.DailyTaskAppService.Login()
   at Ray.BiliBiliTool.Application.DailyTaskAppService.DoDailyTask() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Application/DailyTaskAppService.cs:line 56
   at Ray.BiliBiliTool.Console.Program.StartRun() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 94
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 29
Error: Process completed with exit code 134.

**Comment by Kexueguaixiong** [comment]
会封号吗？？
![Uploading B8143CAE-9CB9-4405-A615-46E8FA39DF0C.png…]()

**Comment by Kexueguaixiong** [comment]
今天弹了个这个
![Uploading 2166C012-F805-477A-9B7E-B0A105999301.png…]()
