### ISSUE TITLE
程序发生异常

### ISSUE THREAD

**Issue by hgfgggg6666** [RayWangQvQ/BiliBiliTool#72]
程序发生异常：One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
30
Unhandled exception. System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
31
 ---> Refit.ApiException: Response status code does not indicate success: 412 (Precondition Failed).
32
   at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 267
33
   --- End of inner exception stack trace ---
34
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
35
   at System.Threading.Tasks.Task`1.get_Result()
36
   at Ray.BiliBiliTool.DomainService.AccountDomainService.LoginByCookie() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.DomainService/AccountDomainService.cs:line 32
37
   at Ray.BiliBiliTool.Application.DailyTaskAppService.Login()
38
   at Ray.BiliBiliTool.Application.DailyTaskAppService.DoDailyTask() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Application/DailyTaskAppService.cs:line 45
39
   at Ray.BiliBiliTool.Console.Program.StartRun() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 94
40
   at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 29
41
Error: Process completed with exit code 134.

**Comment by RayWangQvQ** [comment]
当前版本（V1.0.10）已将UA开放为配置，用于暂时解决412问题，详情见[常见问题4](https://github.com/RayWangQvQ/BiliBiliTool.Docs/blob/main/questions.md)。
